apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgDV2tlzmEuN8IulfK/Xq9IK5goN4u324hp4KJ6hYh7rWiaP5ud7BRw4BnLktQqxKiIeJrbyWKnau0id1Ig5oDq84wYHS6ZyQ9NgZuSkrJnv3mIzVQYyurOYyCC9DfuUYAEWQzcfDuizMiVO+dbw2Kiy0be+RBQ4OZRE/IEl0jXux/MpPaW4+hHsTYgbXuRYHRMED4lc+jElNxV6GkSz2JEaQOfo5bbWXXKOTiJSNrQx06XOYCG0OA6FYaPR0WANfjTveYsz3ssebLxhFfyH6EXdb/YRmiQcvEIW4aTD78HtrXCCNE8psHfzQASZCsM0Cv7LbSZojYRxoXuCz8olsCqMdXjlB1ehUSGZtxQciN5xV4Pou9ggS8FV3xo2OP7gFVrBQtvZHq5HTQnjkv3jBEYRCnV2L9o9frhMOA0icqRRNCK4nWo7Js3kjaWlqKzDRTJ5u4irZiY22nEO1I7kgKe8jndqFw7tEZyzUewGDfLmRmPiPlZd6+BSP9mL8hSP/0rUhsyrpRikWulGtzUbknrJhuWAsqN1u9DMWXUSCKQLHl2HLvbq/LNri3Iowol+bMrvgkjH6YWdgUx4fyRZH6f0XqAjG0TIIJvfwXTycBo6JXZV35/4tGh1VWqEuiiC0yeXhN6VbKf72poOcFJTxNafwHUiofcRuMRv6klr+pUsZ0dBp96YDMAxTKathtAsoN/HzKcDivs=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
