apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAc0NMEOVFIH37D59dbV2GsJvU7uxGAmDOLLQ0WYGoUX3+FteB8Vt7UDkgMZj/6fRBZ7CKoE3gXS/X4UWkaL9zoAzRbhOWCXnW3Db17H8oZvaSW5+wrJ7SEKbRRDat6zfywP/Wb114663Go0E3ziTYF53OmnIEWNj/y6lPZLm4RgmXVHY2i/Ei77MVAVl/N7nP1TbX69/FhSVY6YXFUUJSrEY4chwoHJrRLDJjiDtlpdwdA2X5r6EVSIZmCb+iOzjCUR1j5PEyZzlDdzVGTAIs5Zkdwoua34QCG28jXPJb6MBs5cj7+FwhiT0LTea4I/atpdUk0Mw1CgOr5I+11nb5DkKdl0c5fuj/Q756neLHSC0K+U31wbZZwuef9lO3Ik4N/D2kaz6y90+2uREWRcwrnkuEMJHZ5zyW1OQ/PjtgVvmULMAT34Vbnau+IOj+yxuDpSXkGQnkh2bC+/0Yik2l19ThZ2BaZqnfFqhq6DRo0d4vJEPogwmYyZ9C3te5R/R+EXtT7KsWgJYhpy2u9ggzBDZJq9xyqHk54g7cSpN9LG8bnYPS/aN9hGeP07uZZhtmIjCcCYkDMtohmx/32eNmdvKnK0FOWuwWrJ3ca2Q5lsz8bDC/Tav/Ix7v+UDJEBbPPQY6SeFGYxyHmE16bOCSFx8DvhkX/811t36pa656Hf0UZrrEh1upTn4IPEhb56WWml8KWIrX+5IftWLZ/xCSdRAL+4Q==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
