apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAQyw9htZUTYC4e6nSemAKbeHkZc8aG+M+z8l8Hup3nbmHUfz+tj60XOpdVPXOCwJw+831DfoAOKJfxKHfyoclLb/7saSK9EK5cmKRSA2yXsZqK1eWRFph5qA3b3gc2w3ROHGzqPpFqkcoL14H3a109Uyej0WoloDGdfGPcBmzuyCBEHn9n/6oKomY9QiKHmdeQCB0MRUeajJtTuFby23O3Rf45gU8UNwuhlJBNKloKNF97OPOrUhBrjHkMegDRHhlvRVLUdDjwobCsP8VKZHScer3XPhru9oozIcOO5QihgfwxaOTenHaN8beoHWQ63ydZP5KWAXOaAymJCobD4ZDWJy6rcNONoPBNBUh0b49+4y+fWBSa7O/lqql7bD4cs6WjaPMNfty8nRRSnIBLuyDZ8Dz7OoiqzEXzkSwjCEEU2QPrnbVyCdprS7OgqFXu0ImnOaTxomqdf/Bf/gADRO1hPOSrDtYW4BoynkJguWODX2mixebun+RS8QggzVvSgQlCsvrT9W8RmCf305mWBIdt89BpdF5IRmx3RbEUw/24CGaKvcSb95+ldLGS8ifbZ3UBz88lxUUqynLx+3yEJ0TQgqRiuwP7FMxmrmHPN/jMlDsMeGH0ozU1NR5zgb1ofCuGINHKYm4BEriu9T8OUprUgCwp4EvDZ9lxE+fNK0AYkxam0QQyMH4p8FhSzenLFoD+24EJNPkcuK82b//attqwmVvJgw==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
